[build]
  command = "npm run build"
  publish = "dist"
  functions = "./src/functions"

[context.production]
  environment = { NODE_VERSION = "15.2.0", NODE_ENV = "production" }

[dev]
  command = "npm run watch"
  framework = "#custom"
  publish = "dist"
  port = 3000
  targetPort = 8182
  NODE_ENV = "development"
  functionsPort = 34567

[[redirects]]
  from = "/"
  to = "https://spaceipsum.com/.netlify/functions/random"
  status = 302
  force = true

[[redirects]]
  from = "/random"
  to = "https://spaceipsum.com/.netlify/functions/random"
  status = 302
  force = true

[[redirects]]
  from = "https://spaceipsum.netlify.app/*"
  to = "https://spaceipsum.com/:splat"
  status = 301
  force = true